# Generated by Django 5.0.4 on 2024-04-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_site", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="experience",
        ),
    ]
