# Generated by Django 5.0.4 on 2024-04-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelance_site", "0002_remove_customer_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="profiles/"),
        ),
        migrations.AddField(
            model_name="performer",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="profiles/"),
        ),
    ]
